environment: development
domain: localhost

# Ingress
ingress:
  enabled: false

# Metronome
metronome:
  service:
    type: ClusterIP
    port: 80

# Backend
backend:
  service:
    type: ClusterIP
    port: 80

  container:
    port: 8080

# Secrets
secrets:
  enabled: false

  metronome_api_key:
    key: ""
