environment: development
domain: localhost

# Ingress
ingress:
  enabled: false

# Metronome
metronome:
  service:
    type: ClusterIP
    port: 80

# Secrets
secrets:
  enabled: false

  metronome_api_key:
    key: ""
