environment: production
domain: billing.cleanlab.ai

# Ingress
ingress:
  enabled: true

# Metronome
metronome:
  service:
    type: NodePort
    port: 80
    
# Secrets
secrets:
  enabled: true

  metronome_api_key:
    key: "production/control-plane/metronome-reverse-proxy/metronome_api_key"

  internal_api_keys:
    key: "production/control-plane/internal-api-keys"
