{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-posthog-project-api-key
  labels:
    {{- include "posthog-reverse-proxy.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.environment }}-control-plane-cluster-secret-store
  target:
    name: {{ .Release.Name }}-posthog-project-api-key
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.posthog_project_api_key.key }}
{{- end }}