apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  labels:
    {{- include "codex.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secrets.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secrets.serviceAccountRef.name }}
            namespace: {{ .Release.Namespace }}
