environment:  # development, staging, or production
domain:  # e.g. billing.cleanlab.ai

# Ingress
ingress:
  enabled: true

# Metronome
metronome:
  service:
    port: 80

# Backend
backend:
  service:
    port: 80

  container:
    port: 8080

# Secrets
secrets:
  enabled: true

  metronome_api_key:
    key: ""

  internal_api_keys:
    key: ""
