load("../utils.Tiltfile", "load_env_as_secrets")


def deploy_posthog_reverse_proxy():
    load_env_as_secrets("posthog-reverse-proxy", "services/posthog-reverse-proxy/.env")

    values = [
        "deploy/helm/posthog-reverse-proxy/values.yaml",
        "deploy/helm/posthog-reverse-proxy/values/local.yaml",
    ]

    k8s_yaml(helm(
        "deploy/helm/posthog-reverse-proxy",
        name="posthog-reverse-proxy",
        values=values,
    ))

    k8s_resource(
        "posthog-reverse-proxy",
        port_forwards=[
            port_forward(8080, 80, name="posthog-reverse-proxy"),
        ],
        labels=["posthog-reverse-proxy"],
    )