name: Deploy Infra

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            aws_region:
                required: true
                type: string
        secrets:
            aws_access_key_id:
                required: true
            aws_secret_access_key:
                required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        id: set-env
        run: |
          # Get the infra directory (infra/environments/staging or infra/environments/production)
          infra_dir=infra/environments/${{ inputs.environment }}
          echo "infra_dir=${infra_dir}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}

      - name: tofu apply
        uses: dflook/tofu-apply@v1
        with:
          path: ${{ steps.set-env.outputs.infra_dir }}
          # TODO: consider removing this
          # this prevents us from having to only merge through PRs
          auto_approve: true
