name: Deploy Services

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      region:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy-posthog-reverse-proxy:
    uses: ./.github/workflows/deploy-posthog-reverse-proxy.yml
    with:
      environment: ${{ inputs.environment }}
      cluster_name: ${{ inputs.cluster_name }}
      region: ${{ inputs.region }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-billing:
    uses: ./.github/workflows/deploy-billing.yml
    with:
      environment: ${{ inputs.environment }}
      cluster_name: ${{ inputs.cluster_name }}
      region: ${{ inputs.region }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
