name: Deploy Infra

on:
  push:
    branches:
      - main
      - staging

env:
  aws_region: us-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        id: set-env
        run: |
          # Get the infra directory (infra/environments/staging or infra/environments/main)
          if [ "${{ github.ref_name }}" = "main" ]; then
            infra_dir=infra/environments/production
          elif [ "${{ github.ref_name }}" = "staging" ]; then
            infra_dir=infra/environments/staging
          else
            echo "Invalid branch: ${{ github.ref_name }}"
            exit 1
          fi
          echo "infra_dir=${infra_dir}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}

      - name: tofu apply
        uses: dflook/tofu-apply@v1
        with:
          path: ${{ steps.set-env.outputs.infra_dir }}
          # TODO: consider removing this
          # this prevents us from having to only merge through PRs
          auto_approve: true
