name: Create Tofu plan

on:
  pull_request:
    branches:
      - staging
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  aws_region: us-west-2

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        id: set-env
        run: |
          # Get the infra directory (infra/environments/staging or infra/environments/main)
          infra_dir=infra/environments/${{ github.ref_name }}
          echo "infra_dir=${infra_dir}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}

      - name: tofu plan
        uses: dflook/tofu-plan@v1
        with:
          path: ${{ steps.set-env.outputs.infra_dir }}
