apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-metronome-reverse-proxy-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf.template: |
    events {}
    http {

      limit_req_zone $binary_remote_addr zone=one:10m rate=50r/s;

      server {
        listen {{ .Values.metronome.service.port }};
        server_name {{ .Values.domain }};

        location /ingest {
          if ($http_x_is_cleanlab_origin != "true") {
            return 403;
          }

          limit_req zone=one burst=10 nodelay;

          rewrite ^/ingest$ /v1/ingest break;
          
          proxy_pass https://api.metronome.com;
          proxy_set_header Authorization "Bearer $METRONOME_API_KEY";
          proxy_set_header X-Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
