apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metronome-reverse-proxy
  labels:
    {{- include "billing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metronome.service.type }}
  ports:
    - port: {{ .Values.metronome.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-metronome-reverse-proxy
